favicon: null
name: Go Summit
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.8125
  brandStrength: 0
  lightness: 0.5
  brandColors:
    - '#fc5d3f'
    - '#105d6a'
    - '#ecf1f7'
    - '#73cbce'
    - '#508aba'
  rhythmicContrast: 0.75
typography_spectrum: 0.5
style: the-composer
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.13792409538291395
analytics:
  twitter: null
  google: null
  facebook: null
