cta:
  bucket: null
  version: null
  domain: null
name: Go Summit
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
typography_spectrum: 0.5
color:
  saturation: 0.8125
  brandStrength: 1
  rhythmicContrast: 0.75
  brandColors:
    - '#fc5d3f'
    - '#105d6a'
    - '#ecf1f7'
    - '#73cbce'
    - '#508aba'
  lightness: 0.5
layout_spectrum: 0.6541219
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
